[package]
name = "chatui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
gpui = "0.2.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
unicode-segmentation = "1.12.0"
ureq = { version = "3.1.4", features = ["json"] }
